name: "test AWS Access (fixed version)"

on:
  workflow_dispatch:  # 手动触发最方便

permissions:
  id-token: write      # 必须，有了它 GitHub 才会给你 OIDC token
  contents: read       # checkout 用

jobs:
  aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::814236473104:role/sts-lab-2-target
          role-session-name: OIDCSession

      - name: Show Identity
        run: aws sts get-caller-identity
        shell: bash
        
      - name: List Secrets
        run: |
          echo "=== Listing secrets ==="
          aws secretsmanager list-secrets --region us-east-1
        shell: bash

      - name: Get Policy ARN
        id: getpolicy
        run: |
          ARN=$(aws iam list-attached-role-policies --role-name sts-lab-2-target --query "AttachedPolicies[0].PolicyArn" --output text)
          echo "POLICY_ARN=$ARN" >> $GITHUB_ENV
        shell: bash

      - name: Get Policy Version
        run: aws iam get-policy-version --policy-arn $POLICY_ARN --version-id v1

      - name: Get The Secret
        run: aws secretsmanager get-secret-value --secret-id flag_sts_lab_2
